### ISSUE TITLE
A video is nice, but... 

### ISSUE THREAD

**Issue by Revadike** [rissson/place-timelapse-2022#1]
... can you make it interactive?

https://freestlr.github.io/place/
https://github.com/freestlr/place/issues/1

**Comment by rissson** [comment]
Hi! I'll look into it.

**Comment by rissson** [comment]
The problem is that dumps that we make are not accurate enough to be able to do that kind of rendering. I'll look into using Reddit's dump if they ever publish it, but for now, I guess a timelapse is good enough.

**Comment by Revadike** [comment]
Yeah, I was thinking the same thing. We need the data to be dumped.

**Comment by firekeeper-anna** [comment]
As I mentioned in https://github.com/freestlr/place/issues/1  reddit published the 2017 data here: https://www.reddit.com/r/dataisbeautiful/comments/66ivqs/interactive_timelapse_of_rplace_oc/
I assume there is a high probability they'll do the same with this years data too.

**Comment by exurd** [comment]
> As I mentioned in [freestlr/place#1](https://github.com/freestlr/place/issues/1) reddit published the 2017 data here: https://www.reddit.com/r/dataisbeautiful/comments/66ivqs/interactive_timelapse_of_rplace_oc/ I assume there is a high probability they'll do the same with this years data too.

[The dataset](https://www.reddit.com/r/place/comments/txvk2d/rplace_datasets_april_fools_2022/) has been released.
